% MATLAB code for generating Figure 8 of the manuscript
% Different plots of probability density functions can be generated by
% uncommenting Line number: 264, 267 and 270 of the code for different
% integration schemes.
% The benchmark solution corresponds to g-Weak 1.0 with \Delta t = 10^{-5}s in Line 216.
% The rest of the figures for the different integration schemes are
% obtained for \Delta t = 10^{-2}s in Line 216.
clc
clear
close all
warning off
%
%%
% parameters of Van der Pol SDE
mu = 2; k = 5; epsi = 1.5; sigg = 1; % Original
sig1 = sigg; sig2 = sigg; sig3 = sigg;
%
syms w1 w2 w3 q1 q2 q3
%
qvar = [q1; q2; q3];
wvar = [w1; w2; w3];
%
% Diffusion coefficients
b1 = sig1; b2 = sig2; b3 = sig3;
sigmaw = [b1; b2; b3];
%
% Drift coefficients
aw = [k*acos(q1)/(sqrt(1-(q1)^2))*(1-(q1)^2) - mu*(((w1)^2+(w2)^2+(w3)^2)^(epsi-1))*(q3*w2-q2*w3);
           k*acos(q1)/(sqrt(1-(q1)^2))*(-q1*q2) - mu*(((w1)^2+(w2)^2+(w3)^2)^(epsi-1))*(q1*w3-q3*w1);
           k*acos(q1)/(sqrt(1-(q1)^2))*(-q1*q3) - mu*(((w1)^2+(w2)^2+(w3)^2)^(epsi-1))*(q2*w1-q1*w2)];
%
% Kolmogorov Operators
% Differentiations
A11 = diff(aw(1),w1); A12 = diff(aw(1),w2); A13 = diff(aw(1),w3);
A111 = diff(A11,w1); A122 = diff(A12,w2); A133 = diff(A13,w3);
A112 = diff(A11,w2); A113 = diff(A11,w3); A123 = diff(A12,w3);
%
A21 = diff(aw(2),w1); A22 = diff(aw(2),w2); A23 = diff(aw(2),w3);
A211 = diff(A21,w1); A222 = diff(A22,w2); A233 = diff(A23,w3);
A212 = diff(A21,w2); A213 = diff(A21,w3); A223 = diff(A22,w3);
%
A31 = diff(aw(3),w1); A32 = diff(aw(3),w2); A33 = diff(aw(3),w3);
A311 = diff(A31,w1); A322 = diff(A32,w2); A333 = diff(A33,w3);
A312 = diff(A31,w2); A313 = diff(A31,w3); A323 = diff(A32,w3);
%
B11 = diff(sigmaw(1),w1); B12 = diff(sigmaw(1),w2); B13 = diff(sigmaw(1),w3);
B111 = diff(B11,w1); B122 = diff(B12,w2); B133 = diff(B13,w3);
B112 = diff(B11,w2); B113 = diff(B11,w3); B123 = diff(B12,w3);
%
B21 = diff(sigmaw(2),w1); B22 = diff(sigmaw(2),w2); B23 = diff(sigmaw(2),w3);
B211 = diff(B21,w1); B222 = diff(B22,w2); B233 = diff(B23,w3);
B212 = diff(B21,w2); B213 = diff(B21,w3); B223 = diff(B22,w3);
%
B31 = diff(sigmaw(3),w1); B32 = diff(sigmaw(3),w2); B33 = diff(sigmaw(3),w3);
B311 = diff(B31,w1); B322 = diff(B32,w2); B333 = diff(B33,w3);
B312 = diff(B31,w2); B313 = diff(B31,w3); B323 = diff(B32,w3);
%
% L0a and L0b expressions
L0a1 = aw(1)*A11 + aw(2)*A12 + aw(3)*A13...
              + 0.5*(sigmaw(1))^2*A111 + 0.5*(sigmaw(2))^2*A122 + 0.5*(sigmaw(3))^2*A133...
              + sigmaw(1)*sigmaw(2)*A112 + sigmaw(1)*sigmaw(3)*A113 + sigmaw(2)*sigmaw(3)*A123;
L0a2 = aw(1)*A21 + aw(2)*A22 + aw(3)*A23...
              + 0.5*(sigmaw(1))^2*A211 + 0.5*(sigmaw(2))^2*A222 + 0.5*(sigmaw(3))^2*A233...
              + sigmaw(1)*sigmaw(2)*A212 + sigmaw(1)*sigmaw(3)*A213 + sigmaw(2)*sigmaw(3)*A223;
L0a3 = aw(1)*A31 + aw(2)*A32 + aw(3)*A33...
              + 0.5*(sigmaw(1))^2*A311 + 0.5*(sigmaw(2))^2*A322 + 0.5*(sigmaw(3))^2*A333...
              + sigmaw(1)*sigmaw(2)*A312 + sigmaw(1)*sigmaw(3)*A313 + sigmaw(2)*sigmaw(3)*A323;
L0b1 = aw(1)*B11 + aw(2)*B12 + aw(3)*B13...
              + 0.5*(sigmaw(1))^2*B111 + 0.5*(sigmaw(2))^2*B122 + 0.5*(sigmaw(3))^2*B133...
              + sigmaw(1)*sigmaw(2)*B112 + sigmaw(1)*sigmaw(3)*B113 + sigmaw(2)*sigmaw(3)*B123;
L0b2 = aw(1)*B21 + aw(2)*B22 + aw(3)*B23...
              + 0.5*(sigmaw(1))^2*B211 + 0.5*(sigmaw(2))^2*B222 + 0.5*(sigmaw(3))^2*B233...
              + sigmaw(1)*sigmaw(2)*B212 + sigmaw(1)*sigmaw(3)*B213 + sigmaw(2)*sigmaw(3)*B223;
L0b3 = aw(1)*B31 + aw(2)*B32 + aw(3)*B33...
              + 0.5*(sigmaw(1))^2*B311 + 0.5*(sigmaw(2))^2*B322 + 0.5*(sigmaw(3))^2*B333...
              + sigmaw(1)*sigmaw(2)*B312 + sigmaw(1)*sigmaw(3)*B313 + sigmaw(2)*sigmaw(3)*B323;
%
% L1a and L1b expressions
L1a1 = sigmaw(1)*A11 + sigmaw(2)*A12 + sigmaw(3)*A13;
L1a2 = sigmaw(1)*A21 + sigmaw(2)*A22 + sigmaw(3)*A23;
L1a3 = sigmaw(1)*A31 + sigmaw(2)*A32 + sigmaw(3)*A33;
L1b1 = sigmaw(1)*B11 + sigmaw(2)*B12 + sigmaw(3)*B13;
L1b2 = sigmaw(1)*B21 + sigmaw(2)*B22 + sigmaw(3)*B23;
L1b3 = sigmaw(1)*B31 + sigmaw(2)*B32 + sigmaw(3)*B33;
%
% Differentiations
L0A11 = diff(L0a1,w1); L0A12 = diff(L0a1,w2); L0A13 = diff(L0a1,w3);
L0A111 = diff(L0A11,w1); L0A122 = diff(L0A12,w2); L0A133 = diff(L0A13,w3);
L0A112 = diff(L0A11,w2); L0A113 = diff(L0A11,w3); L0A123 = diff(L0A12,w3);
%
L0A21 = diff(L0a2,w1); L0A22 = diff(L0a2,w2); L0A23 = diff(L0a2,w3);
L0A211 = diff(L0A21,w1); L0A222 = diff(L0A22,w2); L0A233 = diff(L0A23,w3);
L0A212 = diff(L0A21,w2); L0A213 = diff(L0A21,w3); L0A223 = diff(L0A22,w3);
%
L0A31 = diff(L0a3,w1); L0A32 = diff(L0a3,w2); L0A33 = diff(L0a3,w3);
L0A311 = diff(L0A31,w1); L0A322 = diff(L0A32,w2); L0A333 = diff(L0A33,w3);
L0A312 = diff(L0A31,w2); L0A313 = diff(L0A31,w3); L0A323 = diff(L0A32,w3);
%
L0B11 = diff(L0b1,w1); L0B12 = diff(L0b1,w2); L0B13 = diff(L0b1,w3);
L0B111 = diff(L0B11,w1); L0B122 = diff(L0B12,w2); L0B133 = diff(L0B13,w3);
L0B112 = diff(L0B11,w2); L0B113 = diff(L0B11,w3); L0B123 = diff(L0B12,w3);
%
L0B21 = diff(L0b2,w1); L0B22 = diff(L0b2,w2); L0B23 = diff(L0b2,w3);
L0B211 = diff(L0B21,w1); L0B222 = diff(L0B22,w2); L0B233 = diff(L0B23,w3);
L0B212 = diff(L0B21,w2); L0B213 = diff(L0B21,w3); L0B223 = diff(L0B22,w3);
%
L0B31 = diff(L0b3,w1); L0B32 = diff(L0b3,w2); L0B33 = diff(L0b3,w3);
L0B311 = diff(L0B31,w1); L0B322 = diff(L0B32,w2); L0B333 = diff(L0B33,w3);
L0B312 = diff(L0B31,w2); L0B313 = diff(L0B31,w3); L0B323 = diff(L0B32,w3);
%
L1A11 = diff(L1a1,w1); L1A12 = diff(L1a1,w2); L1A13 = diff(L1a1,w3);
L1A111 = diff(L1A11,w1); L1A122 = diff(L1A12,w2); L1A133 = diff(L1A13,w3);
L1A112 = diff(L1A11,w2); L1A113 = diff(L1A11,w3); L1A123 = diff(L1A12,w3);
%
L1A21 = diff(L1a2,w1); L1A22 = diff(L1a2,w2); L1A23 = diff(L1a2,w3);
L1A211 = diff(L1A21,w1); L1A222 = diff(L1A22,w2); L1A233 = diff(L1A23,w3);
L1A212 = diff(L1A21,w2); L1A213 = diff(L1A21,w3); L1A223 = diff(L1A22,w3);
%
L1A31 = diff(L1a3,w1); L1A32 = diff(L1a3,w2); L1A33 = diff(L1a3,w3);
L1A311 = diff(L1A31,w1); L1A322 = diff(L1A32,w2); L1A333 = diff(L1A33,w3);
L1A312 = diff(L1A31,w2); L1A313 = diff(L1A31,w3); L1A323 = diff(L1A32,w3);
%
L1B11 = diff(L1b1,w1); L1B12 = diff(L1b1,w2); L1B13 = diff(L1b1,w3);
L1B111 = diff(L1B11,w1); L1B122 = diff(L1B12,w2); L1B133 = diff(L1B13,w3);
L1B112 = diff(L1B11,w2); L1B113 = diff(L1B11,w3); L1B123 = diff(L1B12,w3);
%
L1B21 = diff(L1b2,w1); L1B22 = diff(L1b2,w2); L1B23 = diff(L1b2,w3);
L1B211 = diff(L1B21,w1); L1B222 = diff(L1B22,w2); L1B233 = diff(L1B23,w3);
L1B212 = diff(L1B21,w2); L1B213 = diff(L1B21,w3); L1B223 = diff(L1B22,w3);
%
L1B31 = diff(L1b3,w1); L1B32 = diff(L1b3,w2); L1B33 = diff(L1b3,w3);
L1B311 = diff(L1B31,w1); L1B322 = diff(L1B32,w2); L1B333 = diff(L1B33,w3);
L1B312 = diff(L1B31,w2); L1B313 = diff(L1B31,w3); L1B323 = diff(L1B32,w3);
% 
% Higher order mixed L0 and L1 expressions
L0L0a1 = aw(1)*L0A11 + aw(2)*L0A12 + aw(3)*L0A13...
              + 0.5*(sigmaw(1))^2*L0A111 + 0.5*(sigmaw(2))^2*L0A122 + 0.5*(sigmaw(3))^2*L0A133...
              + sigmaw(1)*sigmaw(2)*L0A112 + sigmaw(1)*sigmaw(3)*L0A113 + sigmaw(2)*sigmaw(3)*L0A123;
L0L0a2 = aw(1)*L0A21 + aw(2)*L0A22 + aw(3)*L0A23...
              + 0.5*(sigmaw(1))^2*L0A211 + 0.5*(sigmaw(2))^2*L0A222 + 0.5*(sigmaw(3))^2*L0A233...
              + sigmaw(1)*sigmaw(2)*L0A212 + sigmaw(1)*sigmaw(3)*L0A213 + sigmaw(2)*sigmaw(3)*L0A223;
L0L0a3 = aw(1)*L0A31 + aw(2)*L0A32 + aw(3)*L0A33...
              + 0.5*(sigmaw(1))^2*L0A311 + 0.5*(sigmaw(2))^2*L0A322 + 0.5*(sigmaw(3))^2*L0A333...
              + sigmaw(1)*sigmaw(2)*L0A312 + sigmaw(1)*sigmaw(3)*L0A313 + sigmaw(2)*sigmaw(3)*L0A323;
L0L0b1 = aw(1)*L0B11 + aw(2)*L0B12 + aw(3)*L0B13...
              + 0.5*(sigmaw(1))^2*L0B111 + 0.5*(sigmaw(2))^2*L0B122 + 0.5*(sigmaw(3))^2*L0B133...
              + sigmaw(1)*sigmaw(2)*L0B112 + sigmaw(1)*sigmaw(3)*L0B113 + sigmaw(2)*sigmaw(3)*L0B123;
L0L0b2 = aw(1)*L0B21 + aw(2)*L0B22 + aw(3)*L0B23...
              + 0.5*(sigmaw(1))^2*L0B211 + 0.5*(sigmaw(2))^2*L0B222 + 0.5*(sigmaw(3))^2*L0B233...
              + sigmaw(1)*sigmaw(2)*L0B212 + sigmaw(1)*sigmaw(3)*L0B213 + sigmaw(2)*sigmaw(3)*L0B223;
L0L0b3 = aw(1)*L0B31 + aw(2)*L0B32 + aw(3)*L0B33...
              + 0.5*(sigmaw(1))^2*L0B311 + 0.5*(sigmaw(2))^2*L0B322 + 0.5*(sigmaw(3))^2*L0B333...
              + sigmaw(1)*sigmaw(2)*L0B312 + sigmaw(1)*sigmaw(3)*L0B313 + sigmaw(2)*sigmaw(3)*L0B323;
% 
L1L1a1 = sigmaw(1)*L1A11 + sigmaw(2)*L1A12 + sigmaw(3)*L1A13;
L1L1a2 = sigmaw(1)*L1A21 + sigmaw(2)*L1A22 + sigmaw(3)*L1A23;
L1L1a3 = sigmaw(1)*L1A31 + sigmaw(2)*L1A32 + sigmaw(3)*L1A33;
L1L1b1 = sigmaw(1)*L1B11 + sigmaw(2)*L1B12 + sigmaw(3)*L1B13;
L1L1b2 = sigmaw(1)*L1B21 + sigmaw(2)*L1B22 + sigmaw(3)*L1B23;
L1L1b3 = sigmaw(1)*L1B31 + sigmaw(2)*L1B32 + sigmaw(3)*L1B33;
%
L0L1a1 = aw(1)*L1A11 + aw(2)*L1A12 + aw(3)*L1A13...
              + 0.5*(sigmaw(1))^2*L1A111 + 0.5*(sigmaw(2))^2*L1A122 + 0.5*(sigmaw(3))^2*L1A133...
              + sigmaw(1)*sigmaw(2)*L1A112 + sigmaw(1)*sigmaw(3)*L1A113 + sigmaw(2)*sigmaw(3)*L1A123;
L0L1a2 = aw(1)*L1A21 + aw(2)*L1A22 + aw(3)*L1A23...
              + 0.5*(sigmaw(1))^2*L1A211 + 0.5*(sigmaw(2))^2*L1A222 + 0.5*(sigmaw(3))^2*L1A233...
              + sigmaw(1)*sigmaw(2)*L1A212 + sigmaw(1)*sigmaw(3)*L1A213 + sigmaw(2)*sigmaw(3)*L1A223;
L0L1a3 = aw(1)*L1A31 + aw(2)*L1A32 + aw(3)*L1A33...
              + 0.5*(sigmaw(1))^2*L1A311 + 0.5*(sigmaw(2))^2*L1A322 + 0.5*(sigmaw(3))^2*L1A333...
              + sigmaw(1)*sigmaw(2)*L1A312 + sigmaw(1)*sigmaw(3)*L1A313 + sigmaw(2)*sigmaw(3)*L1A323;
L0L1b1 = aw(1)*L1B11 + aw(2)*L1B12 + aw(3)*L1B13...
              + 0.5*(sigmaw(1))^2*L1B111 + 0.5*(sigmaw(2))^2*L1B122 + 0.5*(sigmaw(3))^2*L1B133...
              + sigmaw(1)*sigmaw(2)*L1B112 + sigmaw(1)*sigmaw(3)*L1B113 + sigmaw(2)*sigmaw(3)*L1B123;
L0L1b2 = aw(1)*L1B21 + aw(2)*L1B22 + aw(3)*L1B23...
              + 0.5*(sigmaw(1))^2*L1B211 + 0.5*(sigmaw(2))^2*L1B222 + 0.5*(sigmaw(3))^2*L1B233...
              + sigmaw(1)*sigmaw(2)*L1B212 + sigmaw(1)*sigmaw(3)*L1B213 + sigmaw(2)*sigmaw(3)*L1B223;
L0L1b3 = aw(1)*L1B31 + aw(2)*L1B32 + aw(3)*L1B33...
              + 0.5*(sigmaw(1))^2*L1B311 + 0.5*(sigmaw(2))^2*L1B322 + 0.5*(sigmaw(3))^2*L1B333...
              + sigmaw(1)*sigmaw(2)*L1B312 + sigmaw(1)*sigmaw(3)*L1B313 + sigmaw(2)*sigmaw(3)*L1B323;
%
L1L0a1 = sigmaw(1)*L0A11 + sigmaw(2)*L0A12 + sigmaw(3)*L0A13;
L1L0a2 = sigmaw(1)*L0A21 + sigmaw(2)*L0A22 + sigmaw(3)*L0A23;
L1L0a3 = sigmaw(1)*L0A31 + sigmaw(2)*L0A32 + sigmaw(3)*L0A33;
L1L0b1 = sigmaw(1)*L0B11 + sigmaw(2)*L0B12 + sigmaw(3)*L0B13;
L1L0b2 = sigmaw(1)*L0B21 + sigmaw(2)*L0B22 + sigmaw(3)*L0B23;
L1L0b3 = sigmaw(1)*L0B31 + sigmaw(2)*L0B32 + sigmaw(3)*L0B33;
%
xi = [qvar; wvar];
av = matlabFunction(aw,'vars',{([xi])});
L0av = matlabFunction([L0a1;L0a2;L0a3],'vars',{([xi])});
L1av = matlabFunction([L1a1;L1a2;L1a3],'vars',{([xi])});
L0bv = matlabFunction([L0b1;L0b2;L0b3],'vars',{([xi])});
L1bv = matlabFunction([L1b1;L1b2;L1b3],'vars',{([xi])});
L0L0av = matlabFunction([L0L0a1;L0L0a2;L0L0a3],'vars',{([xi])});
L0L0bv = matlabFunction([L0L0b1;L0L0b2;L0L0b3],'vars',{([xi])});
L0L1av = matlabFunction([L0L1a1;L0L1a2;L0L1a3],'vars',{([xi])});
L1L0av = matlabFunction([L1L0a1;L1L0a2;L1L0a3],'vars',{([xi])});
L1L1av = matlabFunction([L1L1a1;L1L1a2;L1L1a3],'vars',{([xi])});
L1L0bv = matlabFunction([L1L0b1;L1L0b2;L1L0b3],'vars',{([xi])});
L0L1bv = matlabFunction([L0L1b1;L0L1b2;L0L1b3],'vars',{([xi])});
L1L1bv = matlabFunction([L1L1b1;L1L1b2;L1L1b3],'vars',{([xi])});
%
%% Initial value
GR = 100;
[X1,Y1,Z1] = sphere(GR-1);
%
qin = Z1(:,1);
qdin = linspace(-5,5,GR);
[p1,p2] = meshgrid(qin, qdin);
[pz1_temp,~] = meshgrid(X1(:,7), qdin);
px1 = pz1_temp(:);
pairs = [p1(:) p2(:)];
%
%% Parameters
T = 1;
fs = 100000; % 100000 for benchmark and 100 for others;
dt = 1/fs;
t = 0:dt:T-dt;
N = T*fs;
%
parfor i = 1:length(pairs)
    disp(i);
%
q = zeros(3,length(t));
qd = zeros(3,length(t));
w = zeros(3,length(t));
q(:,1) = [px1(i);0;pairs(i,1)];
qd(:,1) = [0.01;0.05;pairs(i,2)];
w(:,1) = cross(q(:,1),qd(:,1));
 % Simulation over samples
for l = 2:N
  %
dB1_w = sqrt(dt)*randn;
dB2_w = sqrt(dt)*randn;
dB3_w = sqrt(dt)*randn;
%
% MSIs
Iw_w=dB1_w;
Iws_w=0.5*dt*(dB2_w+dB3_w/sqrt(3)); 
Isw_w=0.5*dt*(dB2_w-dB3_w); 
Iww_w=0.5*(dB1_w*dB1_w-dt); 
Iss_w = 0.5*(dt)^2;
Iwww_w=(1/6)*(Iw_w*Iw_w-3*dt)*Iw_w;
Iwss_w=1/6*Iw_w*dt^2;
Isww_w = 1/6*(Iw_w*Iw_w-dt)*dt;
Isss_w = 1/6*dt^3; 
%
var = [q(:,l-1);w(:,l-1)];
a = av(var);
L0a = L0av(var);
L1a = L1av(var);
L0b = L0bv(var);
L1b = L1bv(var);
L0L0a = L0L0av(var);
L0L0b = L0L0bv(var);
L0L1a = L0L1av(var);
L1L0a = L1L0av(var);
L1L1a = L1L1av(var);
L1L0b = L1L0bv(var);
L0L1b = L0L1bv(var);
L1L1b = L1L1bv(var);
%
% g-Weak 1.0
             w(:,l) = w(:,l-1) + a*dt + sigmaw*dB1_w;
%
% g-Weak 2.0
            % w(:,l) = w(:,l-1) + a*dt + sigmaw*dB1_w + L0a*Iss_w +L1b*Iww_w + L1a*Iws_w + L0b*Isw_w;
%
%  g-Weak 3.0 scheme
            % w(:,l) = w(:,l-1) + a*dt + sigmaw*dB1_w + L0a*Iss_w +L1b*Iww_w + L1a*Iws_w...
            %                  + L0b*Isw_w + L0L0a*Isss_w + (L0L0b + L0L1a + L1L0a)*Iwss_w...
            %                  + (L1L1a + L1L0b + L0L1b)*Isww_w + L1L1b*Iwww_w;
%
        Omega = so3_wedge(w(:,l))*dt;
        %
        q(:,l) = so3_exp_new(Omega)*q(:,l-1);
        %   
        qd(:,l) = cross(w(:,l),q(:,l));
        end
%
    X = [q(:,end);qd(:,end)];
    qval1(i) = X(1);
    qdval1(i) = X(4);
end
%
%% Plotting Basin Stability
xx = [qval1;qdval1]';
figure
ksdensity(xx,pairs);
%
ax = gca;
% 
view(ax,[-37.5 30]);
grid(ax,'on');
% 
ax.FontName   = 'Times New Roman';
ax.FontSize   = 20;
ax.FontWeight = 'bold';
ax.LineWidth  = 1.0;            
ax.TickDir    = 'out'; 
%
ax.XTick = [-1  0  0.5];
ax.YTick = [-5  0  5];
ax.ZTick = [0 0.1 0.2 0.3];
%
xlabel('q','FontName','Times New Roman','FontSize',20,'FontWeight','bold');
ylabel('$\dot{\bf{q}}$','FontWeight','bold','FontName','Times New Roman','Interpreter','latex');
zlabel('pdf', 'FontName','Times New Roman','FontSize',20,'FontWeight','bold');
title('g-Weak 1.0','FontName','Times New Roman','FontSize',20,'FontWeight','bold');
% Change the title according to the integration scheme used
%
% End